[package]
name = "goblinoats-blind-rsa"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4.6"
num-bigint-dig = "0.8.4"
num-integer = "0.1.46"
num-traits = "0.2.19"
rand = "0.8.5"
rsa = "0.9.6"
sha2 = "0.10.8"
