[package]
name = "jackddouglas"
version = "0.1.0"
edition = "2021"

[dependencies]
Gen_Prime = "1.1.9"
num = "0.4.3"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-integer = "0.1.46"
num-prime = "0.4.4"
num-primes = "0.3.0"
num-traits = "0.2"
rand = "0.8"
rayon = "1.10.0"
